import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../public/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to IMDB Graph
        </h1>

        <p className={styles.description}>
          Search for your favorite TV show.
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Source code &rarr;</h2>
            <p>IMDB Graph is 100% open source. Click here to see the GitLab page</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.linkedin.com/in/aria-amini/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Spruce Technologies
          <span className={styles.logo}>
            <Image src="/linkedin.svg" alt="LinkedIn Logo" width={24} height={24} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
